import {AdditonalFactionProps} from "./FactionItem";

let data: AdditonalFactionProps[] = [
    {
        name: "",
        number: 911,
        additionalImage: "",
        text: "Der Notruf ist für Notfälle gedacht. Bitte benutze ihn nicht für Scherzanrufe oder ähnliches.",
        workingHours: "24/7",
        type: "Behörde",
    },
    {
        name: "",
        number: 0,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 1338,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 1339,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 1340,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 922,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 933,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 909,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 5555,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Dienstleistung",
    },
    {
        name: "",
        number: 919,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Dienstleistung",
    },
    {
        name: "",
        number: 1213,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Dienstleistung",
    },
    {
        name: "",
        number: 222,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Dienstleistung",
    },
    {
        name: "",
        number: 912,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Medizin",
    },
    {
        name: "",
        number: 187,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Behörde",
    },
    {
        name: "",
        number: 190,
        additionalImage: "",
        text: "Die Bürgerhotline ist für allgemeine Anfragen und Informationen gedacht.",
        workingHours: "Mo-Fr 9-17 Uhr",
        type: "Behörde",
    },
    {
        name: "Stadtverwaltung",
        number: 999,
        additionalImage: "",
        text: "Die Stadtverwaltung ist für allgemeine Anfragen und Informationen gedacht.",
        workingHours: "Mo-Fr 19-22 Uhr",
        type: "Behörde",
    }, {
        name: "United States Marshals Service",
        number: 944,
        additionalImage: "",
        text: "Frag nicht so blöd, ruf einfach an.",
        workingHours: "24/7",
        type: "Behörde",
    },
    {
        name: "Autoclub Los Santos",
        number: 321,
        additionalImage: "",
        text: "Der Autoclub Los Santos ist für Pannenhilfe und Abschleppdienste gedacht.",
        workingHours: "24/7",
        type: "Werkstatt",
    }, {
        name: "",
        number: 111,
        additionalImage: "",
        text: "",
        workingHours: "",
        type: "Werkstatt",
    },
    {
        name: "",
        number: 456123,
        additionalImage: "",
        text: "Was sollen wir sagen. Fuck YOU!",
        workingHours: "Wenn wir verfickt nochmal bock haben!",
        type: "Handel",
    },
    {
        name: "",
        number: 456,
        additionalImage: "",
        text: "",
        workingHours: "immer",
        type: "Tuning",
    },
    {
        name: "",
        number: 123,
        additionalImage: "",
        text: "",
        workingHours: "immer",
        type: "Tuning",
    },
]

export default data;